version: '3.4'

services:

  # This is the database container. The exposed volume means that the SQL DATA and LOG files
  # are stored off the container, in case the container is restarted.
  umbdata:
    build:
      context: ./Umbdata
      dockerfile: Dockerfile
    ports:
     - "1433:1433"
     - "1434:1434"
    volumes:
     - database:/var/opt/mssql
    networks:
      - umbnet

  # This is the web container. It exposes the port 80, and stored media and Umbraco logs on
  # a volume so they are accessable outside the container.
  # It 
  umbweb:
    build:
      context: ./UmbDock
      dockerfile: Dockerfile
    volumes:
      - media:/app/wwwroot/media
      - logs:/app/umbraco/Logs
    restart: always
    environment:
     - ASPNETCORE_ENVIRONMENT=Production
    # This is the external port the website will be visible from : http://localhost:5080/
    # The Umbraco URL is : http://localhost:5080/umbraco
    ports:
      - "5080:80"
    depends_on:
      - umbdata
    networks:
      - umbnet        


  # This is the 2nd web container. It exposes the port 80, and stored media and Umbraco logs on
  # a volume so they are accessable outside the container.
  # It 
  umbweb-2:
    build:
      context: ./UmbDock
      dockerfile: Dockerfile
    volumes:
      - media:/app/wwwroot/media
      - logs:/app/umbraco/Logs
    restart: always
    environment:
     - ASPNETCORE_ENVIRONMENT=Production
    # This is the external port the website will be visible from : http://localhost:5081/
    # The Umbraco URL is : http://localhost:5081/umbraco
    ports:
      - "5081:80"
    depends_on:
      - umbdata
    networks:
      - umbnet        


volumes:
  media:
  logs:
  database:

# This is the network that the containers will be on, and will ONLY contain the containers from the application
networks:
  umbnet:
    driver: bridge